services:
  seg_and_track:
    build:
      context: .
      dockerfile: services/seg_and_track/Dockerfile
    volumes:
      - ./common_packages:/common_packages
      - file_storage_data:/data
    networks:
      - assistant-network

networks:
  assistant-network:
    driver: bridge

volumes:
  intent_catcher_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: volumes/intent_catcher
  ssml_tagger_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: volumes/ssml_tagger
  file_storage_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: volumes/file_storage
  assistant_db_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: volumes/assistant_db